first_name = input("What is your First Name? ")
last_name = input("What is your Last Name? ")
email_address = input("What is your Email Address? ")
phone_number = input("What is your Phone Number? ")
job_title = input("What is your Job Title? ")
id_number = input("What is your ID Number? ")

print()
print(f"-----------------------------------------")
print(f"Your name is {first_name.upper()}, {last_name}.")
print(f"Job Title: {job_title.capitalize()}")
print(f"ID Number: {id_number}")
print()
print(f"Email Address: {email_address.lower()}.")
print(f"Phone Number: {phone_number}")
print(f"-----------------------------------------")